### ISSUE TITLE
Ajout d'un bouton création de compte dans la navbar

### ISSUE THREAD

**Issue by ThomasEscorne** [NicoMilk/cfscc_front#1]
Dans la navbar il n'y a qu'un bouton pour se connecter, si on veut créer un compte on est obligé de cliquer sur les boutons "créer un compte et m'inscrire" sur une activité.
Ajoute un moyen de créer un compte accessible depuis la navbar (qui n'apparait que si l'utilisateur n'est pas déjà connecté)

**Comment by NicoMilk** [comment]
C'est volontaire : Un utilisateur lambda n'est pas supposé pouvoir créer un compte sans au moins participer a un des évènements accessibles aux non-membres (les membres étant ceux qui cotisent à l'asso), ceci afin d'éviter les comptes fantômes.
Si l'utilisateur souhaite ensuite devenir membre de l'asso, c'est un admin qui change son role (de "guest" à "member").
Ceci dit, s'il faut que je rajoute le bouton pour la keynote, je le fais !

**Comment by NicoMilk** [comment]
Fonction ajoutée a la navbar, deploiement en cours.
